# Generated by Django 5.2.4 on 2025-11-23 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('data', models.BinaryField()),
                ('transcribed_text', models.TextField(blank=True, null=True)),
                ('srt_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_text', models.BooleanField(default=False)),
                ('is_subtitle', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال انجام'), ('done', 'انجام شد'), ('failed', 'ناموفق')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
